POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "VSCode REST client is a pretty handy tool",
    "important": false
}

###
DELETE http://localhost:3001/api/notes/6696b674287f8a47cec41faf