POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "The Raleigh Grand Prix Series",
  "author": "Sheldon Brown",
  "url": "https://www.sheldonbrown.com/retroraleighs/grand-prix.html",
  "likes": 2
}

###
GET http://localhost:3003/api/blogs

###
